[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "luxonis-u2if"
version = "0.0.1"
description = "Python package for controlling Luxonis u2if based devices and library for low level commnucation."
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "Luxonis"}]
license = {text = "MIT"}
keywords = ["rp2040", "u2if", "hid", "controller-box"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["hidapi"]

[project.urls]
"Homepage" = "https://github.com/luxonis/rp2040_u2if"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
