identifier = "com.example.pose-estimation.hand-pose.m8-controller-box"
entrypoint = ["bash", "-c", "/usr/bin/runsvdir -P /etc/service"]
app_version = "1.0.2"
assign_frontend_port = true

prepare_container = [
    { type = "COPY", source = "./requirements.txt", target = "./requirements.txt" },
    { type = "RUN", command = "python3.12 -m pip install -r /app/requirements.txt --break-system-packages"},
    { type = "RUN", command = "bash -lc 'set -e; apt-get update && apt-get install -y libhidapi-hidraw0 libhidapi-libusb0'" }
]

build_steps = [
    "mkdir -p /etc/service/backend",
    "cp /app/backend-run.sh /etc/service/backend/run",
    "chmod +x /etc/service/backend/run",
]

depthai_models = { yaml_path = "./depthai_models" }

allowed_devices = [{ allow = true, access = "rwm" }]

additional_mounts = [
    { source = "/dev", target = "/dev", type = "devtmpfs", options = [
        "mode=777",
    ] }
]

[base_image]
api_url = "https://registry-1.docker.io"
service = "registry.docker.io"
oauth_url = "https://auth.docker.io/token"
auth_type = "repository"
auth_name = "luxonis/oakapp-base"
image_name = "luxonis/oakapp-base"
image_tag = "1.2.6"
